config/routes.rb
Rails.application.routes.draw do
  resources :team_pokemons, only: [:destroy]
  resources :pokemons
  resources :teams, only: [:new, :create, :destroy] do 
    resources :team_pokemons, only: [:new, :create]
  end
  resources :users do
    resources :teams, only: [:index, :show]
  end

  root 'welcome#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/index', to: 'users#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/search', to: 'pokemons#search', as: 'search'

end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :team_pokemons
    has_many :teams, through: :team_pokemons
    scope :search, -> (query) { self.where("name LIKE ?", "%#{query}%") }

    def self.pokemon_data(id)
        information = {
            "name" => [],
            "abilities" => [],
            "types" => [],
            "moves" => [],
            "sprites" => [] }
        pokemon = Pokemon.find(id)
        @info = HTTParty.get(pokemon.url)
        information["name"] << pokemon.name
        @info["abilities"].each do |x|
            information["abilities"] << x["ability"]["name"]
        end
        @info["types"].each do |x|
          information["types"] << x["type"]["name"]
        end
        @info["moves"].each do |x|
          information["moves"] << x["move"]["name"]
        end
        @info["sprites"].each do |x|
            information["sprites"] << x
        end
        return information
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    include PokemonsHelper
    
    def index
        @pokemons = Pokemon.search(params[:name])
    end

    def show
        @info = Pokemon.pokemon_data(params[:id])
    end

    def search
        @pokemon = Pokemon.search(params[:name])
        redirect_to pokemons_path
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper

end

app/views/pokemons/index.html.erb
<h1> PokeDex </h1>
<br>
<%= button_to "Home", "users", method: "get" %>
<br>
<% @pokemons.each do |pokemon| %>
<li><%= link_to(pokemon.name.capitalize, pokemon_path(pokemon.id)) %></li>
<% end %>

app/views/pokemons/search.html.erb
<% form_tag pokemon_path, method: "get", do %>
<%= text_field(:name, "", placeholder "Search for Pokemon") %>
<%= submit_tag %>
<% end %>

app/views/pokemons/show.html.erb
<h1> <%=@info["name"].first.capitalize %> </h1>
Types: <%=@info["types"].join(", ")%>
<br>
<br>
Abilities: <%=@info["abilities"].map {|x| x.capitalize}.join(", ") %>
<br>
<br>
Moves: <%=@info["moves"].map {|x| x.capitalize}.join(", ") %> 
<br>
<br>
<br>
<%= button_to 'Back to Pokedex', '/pokemons', method: "get" %>