config/routes.rb
Rails.application.routes.draw do
  resources :team_pokemons, only: [:destroy]
  resources :pokemons
  resources :teams, only: [:new, :create, :destroy] do 
    resources :team_pokemons, only: [:new, :create]
  end
  resources :users do
    resources :teams, only: [:index, :show]
  end

  root 'welcome#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/index', to: 'users#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/search', to: 'pokemons#search', as: 'search'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand"><%= image_tag 'ball.png' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      </li>
       <% if logged_in? %>
            <li>
                <%= link_to 'Pokedex', pokemons_path, class: 'nav-link active' %>
            </li>
            <li>
                <%= link_to 'Teams', user_teams_path(current_user.id), class: 'nav-link active' %>
            </li>
            <li>
                <%= link_to 'Logout', logout_path, class: 'nav-link active', method: "post" %>
            </li>
        <% else %>
            <li>
                <%= link_to 'LOGIN', login_path, class: 'nav-link active' %>
            </li>
            <li>
                <%= link_to 'SIGNUP', signup_path, class: 'nav-link active' %>
            </li>
            <li>
                <%= link_to 'LOGIN WITH GOOGLE', "/auth/google_oauth2", class: 'nav-link active', method: "post" %>
            </li>
        <% end %>

    </ul>
<%= form_tag pokemons_path, method: "get", html: { class: 'd-flex'} do %>
    <%= text_field_tag(:name, "", class: "form-control me-2", placeholder: "Search for Pokemon")  %>
    <%=  submit_tag :Search, class: "btn btn-outline-success" %>
<% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeRails</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body></body>
  <%= render partial: "layouts/navbar" %>
  <%= flash[:message] %>
    <%= yield %>
  </body>
</html>